from .test_analyze import test_analyze
from .test_autom8 import test_autom8
from .test_latest import test_latest
from .test_lr_normalizer import test_lr_normalizer
from .test_predict import test_predict
from .test_random_methods import test_random_methods
from .test_reducers import test_reducers
from .test_rest import test_rest
from .test_scan import test_scan
from .test_templates import test_templates
