"""Require complete package measurement and at least 80% statement coverage."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def _counts(summary: dict[str, object]) -> tuple[int, int]:
    covered, total = summary['covered_lines'], summary['num_statements']
    if type(covered) is not int or type(total) is not int:
        raise ValueError('coverage counts must be integers')
    if not 0 <= covered <= total:
        raise ValueError('coverage counts must satisfy 0 <= covered <= total')
    return covered, total


def check_statement_coverage(report: Path, package: Path) -> tuple[int, int]:
    """Reject narrowed, inconsistent or below-threshold package reports."""
    package = package.resolve()
    payload = json.loads(report.read_text(encoding='utf-8'))
    files = payload['files']
    expected = {path.resolve() for path in package.rglob('*.py')}
    observed = {(package.parent / name).resolve() for name in files}
    if observed != expected or len(observed) != len(files):
        raise ValueError('coverage report must contain every package module exactly once')
    counts = [_counts(value['summary']) for value in files.values()]
    covered = sum(value[0] for value in counts)
    total = sum(value[1] for value in counts)
    if (covered, total) != _counts(payload['totals']) or not total:
        raise ValueError('coverage totals must match the complete package measurement')
    if covered * 100 < total * 80:
        raise ValueError(f'statement coverage {covered}/{total} is below 80%')
    return covered, total


def main() -> None:
    """Validate the JSON report generated by the full-framework CI lane."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('report', type=Path)
    args = parser.parse_args()
    package = Path(__file__).resolve().parents[1] / 'talos'
    covered, total = check_statement_coverage(args.report, package)
    print(f'Talos statement coverage: {covered}/{total} ({100 * covered / total:.2f}%)')


if __name__ == '__main__':
    main()
